#20 Footer
novvember/lubimovka-landing pull request #45
Opened 2022-06-20 16:58 UTC by akimoveduard

2022-06-21 09:31 UTC, novvember commented
Добавил комментарии к коду
- ты очень детально сверстал, но не уверен, что стоило сохранять все расстояния вплоть до половины пикселя, часто там просто ошибки в макете
- еще не уверен, что нужно было выделять столько самостоятельных блоков

2022-06-21 09:31 UTC, novvember requested changes

2022-06-21 09:31 UTC, novvember commented on index.html
> +        <div class="footer-grid__logo footer-blocks__logo"><img class="footer__logo" src="./images/lubimovka.svg" alt="Логотип Любимовка"></div>
`img` так же можно размещать без дополнительной обертки в `div`

2022-06-21 09:31 UTC, novvember commented on index.html
> +              <a href="#" class="footer__link footer-logos__link footer-logos_name_fond" title="Генеральный партнер Фонд Михаила Прохорова"></a>
Почему ты убрал логотипы партнеров в фоновые изображения? Вроде бы, это вполне контентные картинки

2022-06-21 09:31 UTC, novvember commented on index.html
> +        <ul class="footer-grid__menu-lubimovka footer-blocks__list-lubimovka footer-links-list">
Эта и следующая колонка — это один блок с разделами этого сайта (эти же ссылки повторяются в шапке), поэтому их нужно объединить в один блок, желательно `nav`

2022-06-21 10:07 UTC, akimoveduard commented on index.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
Забыл убрать. Мне нужно это было, чтобы понимать, где верстка не влезает в разрешение. А Хром в этих случаях начинает уменьшать масштаб и вводит в заблуждение. Да, надо убрать.

2022-06-21 10:09 UTC, akimoveduard commented on index.html
> +          <h3 class="footer-blocks__partners-title footer__title">Генеральные партнеры</h3>
Ну вот не знаю, незначимый семантически блок. Честно говоря, особой разницы нет. В прошлом групповом проекте я тоже отстаивал в футере h2, но меня убедили, что h3 лучше. Могу поменять.

2022-06-21 10:11 UTC, akimoveduard commented on index.html
> +              <a href="#" class="footer__link footer-logos__link footer-logos_name_fond" title="Генеральный партнер Фонд Михаила Прохорова"></a>
Там есть проблема: на низких разрешениях под некоторыми логотипами появляются надписи "генеральный партнер" и "онлайн-трансляции". Я не захотел их добавлять текстом, а потом скрывать в CSS, поэтому я сделал эти надписи псевдоэлементами, а у img псевдоэлементы не работают, поэтому пришлось img переделать в фоновые изображения ссылок.

2022-06-21 10:13 UTC, akimoveduard commented on blocks/footer-logos.css
> +    margin-right: 31px;
Я потратил кучу времени, чтобы все было по PixelPerfect, и ты хочешь, чтобы я это уничтожил? :))

2022-06-21 10:34 UTC, akimoveduard commented on index.html
> +              <a href="#" class="footer__link footer-logos__link footer-logos_name_fond" title="Генеральный партнер Фонд Михаила Прохорова"></a>
Ну вот этого я как раз и не хотел. :)) Но могу сделать так. Проблем, кстати, меньше. Я заколебался эти псевдоэлементы выстраивать.

2022-06-21 10:34 UTC, novvember commented on blocks/footer-logos.css
> +    margin-right: 31px;
Тогда не трогаем)  Но у последнего элемента не должно быть margin-right. Тогда можно сделать общий элемент link со всеми размерами и отступами по умолчанию. А для конкретных логотипов-элементов эти параметры перезадавать.

2022-06-21 13:53 UTC, akimoveduard commented on index.html
> +        <ul class="footer-grid__menu-lubimovka footer-blocks__list-lubimovka footer-links-list">
Если я объединяю их в nav, то nav становится ячейкой grid и ломает мне немного структуру. Придется CSS переписать, это займет какое-то время.

2022-06-23 08:17 UTC, novvember approved these changes
Всегда есть, что доводить до совершенства, но сейчас всё тоже работает хорошо.

2022-06-23 08:19 UTC, merged